server:
  port: 8079

# 开发环境配置
spring:
  cloud:
    inetutils:
      preferred-networks: 192.168.3
    nacos:
      discovery:
        server-addr: 192.168.3.15:8848
      config:
        server-addr: 192.168.3.15:8848
  redis:
    host: 192.168.3.15  # Redis服务器地址
    port: 6379          # Redis端口
    password:          # Redis密码（如果有）
    database: 0         # Redis数据库索引
    timeout: 3000ms    # 连接超时时间
    lettuce:
      pool:
        max-active: 8   # 连接池最大连接数
        max-wait: -1ms  # 连接池最大阻塞等待时间
        max-idle: 8     # 连接池中的最大空闲连接
        min-idle: 0     # 连接池中的最小空闲连接

# RestTemplate配置
rest:
  template:
    connect-timeout: 3000
    read-timeout: 5000